[package]
name = "pwvucontrol"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7.1", package = "gtk4", features = ["v4_10"]}
glib = { version = "0.18", features = ["log"] }
log = "0.4.11"
im-rc = "15.1.0"
once_cell = "1.15.0"
wireplumber = { git = "https://github.com/arcnmx/wireplumber.rs.git", rev = "341b0c4e8d177f5f21c109cf88cca4f2dc1f853a", features = ["v0_4_12"] }
#wireplumber = { git = "https://github.com/saivert/wireplumber.rs.git", branch = "use_pipewire_from_git", features = ["v0_4_12"] }
futures = "0.3"
anyhow = "1.0"
pipewire = "0.7"
#pipewire = {git = "https://gitlab.freedesktop.org/saivert/pipewire-rs", branch = "misc_fixes", features = ["v0_3_44"]}

[dependencies.adw]
package = "libadwaita"
version = "0.5"
features = ["v1_2"]
